In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

#### What's the version of NumPy & Pandas that you installed?

In [2]:
np.__version__


'1.19.5'

In [3]:
pd.__version__


'1.1.5'

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

In [5]:
df

Make       Model  Year  ... city mpg  Popularity   MSRP
0          BMW  1 Series M  2011  ...       19        3916  46135
1          BMW    1 Series  2011  ...       19        3916  40650
2          BMW    1 Series  2011  ...       20        3916  36350
3          BMW    1 Series  2011  ...       18        3916  29450
4          BMW    1 Series  2011  ...       18        3916  34500
...        ...         ...   ...  ...      ...         ...    ...
11909    Acura         ZDX  2012  ...       16         204  46120
11910    Acura         ZDX  2012  ...       16         204  56670
11911    Acura         ZDX  2012  ...       16         204  50620
11912    Acura         ZDX  2013  ...       16         204  50920
11913  Lincoln      Zephyr  2006  ...       17          61  28995

[11914 rows x 16 columns]

### What's the average price of BMW cars in the dataset?

In [44]:
df[df["Make"] == "BMW"].MSRP.mean()

61546.76347305389

#### Question 4
#### Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [8]:
after2015 = df[df['Year'] >= 2015]

In [11]:
after2015['Engine HP'].isnull().sum()

51

Question 5
Calculate the average "Engine HP" in the dataset.
####Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
#### Now, calcualte the average of "Engine HP" again.
Has it changed?

In [16]:
avg_HP = df['Engine HP'].mean()
avg_HP

249.38607007176023

In [17]:
df["Engine HP"].fillna(avg_HP)

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
         ...  
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: Engine HP, Length: 11914, dtype: float64

In [19]:
avg_HP_after = df['Engine HP'].mean()
avg_HP_after

249.38607007176023

In [20]:
print(round(avg_HP))
print(round(avg_HP_after))

249
249


### Q6 
### Select all the "Rolls-Royce"cars from the dataset.
###Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
###Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
###Get the underlying NumPy array. Let's call it X.
###Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
###Invert XTX.
###What's the sum of all the elements of the result?

In [21]:
RR = df[df["Make"] == "Rolls-Royce"]

In [24]:
RR_3 = RR[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [25]:
RR_3

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [26]:
RR_3_dropdups = RR_3.drop_duplicates()
RR_3_dropdups

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [29]:
X = np.array(RR_3_dropdups)

In [31]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [32]:
XTX = np.matmul(X.T, X) 

In [33]:
XTX_inverted = np.linalg.inv(XTX)

In [35]:
XTX_inverted

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [34]:
np.sum(XTX_inverted)

0.032212320677486125

### Q7
### Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
####Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
####What's the value of the first element of w?.

In [36]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [40]:
w1 = np.dot(XTX_inverted, X.T)

In [41]:
w = np.dot(w1 , y)

In [42]:
w

array([ 0.19989598, 31.02612262, 31.65378877])